apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - image: wordpress
        name: wp
        env: 
           - name: WORDPRESS_DB_HOST
             value: dbborealis.mysql.database.azure.com
           - name: WORDPRESS_DB_USER
             value: dbborealis
           - name: WORDPRESS_DB_PASSWORD
             value: Welcome12#
           - name: WORDPRESS_DB_NAME
             value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp
  name: wp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp
  type: LoadBalancer
